#!/bin/bash


#======================================
#   Variables
#======================================

asset_dirs=( 'container--widgets'
             'button--widgets'
             'menu-icons'
             'misc--widgets'
             'overview--widgets'
             'panel--widgets'
             'control--widgets' )

tmp_dir=".tmp"

css_file="gnome-shell.css"

gresource_dest="../../gnome-shell-theme.gresource"


#======================================
#   Copy all assets into tmp_dir
#
#   GDM seems to have some trouble
#   when the assets aren't in the same
#   dir as the .xml file
#======================================

echo -e "\e[34mGenerating gresource file...\e[0m"

trap 'rm -rf $tmp_dir; exit' INT TERM EXIT

mkdir -p "$tmp_dir"

find "${asset_dirs[@]}" -type f -execdir cp -f {} "$PWD/$tmp_dir/" \;


#======================================
#   Modify urls paths in css file
#======================================

printf -v regex "%s/|" "${asset_dirs[@]}"

regex=${regex%|}  # remove trailing "|"

sed -r "s:$regex::" "$css_file" > "$tmp_dir/gnome-shell.css"


#======================================
#   Create gresource.xml file
#======================================

echo "<?xml version='1.0' encoding='UTF-8'?><gresources><gresource prefix='/org/gnome/shell/theme'>" \
     > "$tmp_dir/gnome-shell-theme.gresource.xml"


for i in "$tmp_dir"/*; do
    [ "${i##*.}" != "svg" ] && [ "${i##*.}" != "png" ] && continue

    echo "<file preprocess='to-pixdata'>${i##*/}</file>" \
         >> "$tmp_dir/gnome-shell-theme.gresource.xml"
done


echo "<file>gnome-shell.css</file></gresource></gresources>" \
     >> "$tmp_dir/gnome-shell-theme.gresource.xml"


#======================================
#   Create gresource file
#======================================

glib-compile-resources --sourcedir="$tmp_dir" \
                       --target="$gresource_dest" \
                       "$tmp_dir/gnome-shell-theme.gresource.xml"


echo -e "\e[32mGresource file generated!\e[0m"
